### PR TITLE
Allow specifying agent host in config

### LINKED ISSUE #47: How to set Jaeger endpoint
Hi, i try to use the python version of the jaeger client.
 In go i do that to create the tracer : 

```go
cfg := jaegercfg.Configuration{
		Sampler: &jaegercfg.SamplerConfig{
			Type:  jaeger.SamplerTypeConst,
			Param: 1,
		},
		Reporter: &jaegercfg.ReporterConfig{
		LogSpans:           true,
		LocalAgentHostPort: "192.168.1.10:5775",
	},
}

jLogger := jaegerlog.StdLogger
jMetricsFactory := metrics.NullFactory
tracer, _, err := cfg.New(
		"myservice",
		jaegercfg.Logger(jLogger),
		jaegercfg.Metrics(jMetricsFactory),
)
```

How do that in Python ?
Thanks

### PR DESCRIPTION
**Pull request by bendemaree**
This allows setting the Jaeger agent host to something other than `localhost` in config. This scenario is also noted in #47 and this implementation follows the notes given there.

Fixes #47

### CODE REVIEW

**Comment by bharat-p** [comment]
Hey @bendemaree were you able to get it to work to send span/trace to agent running in docker all-in-one image running on a remote host. I am trying to get it to work but so far no luck.

**Comment by yurishkuro** [comment]
@bendemaree do you mind adding a unit test?

**Comment by bharat-p** [comment]
Update: So I was able to get traces sent to remote agent, when agent was running in a VM ( via virtualbox) on same mac where client was.

When Jaeger agent was on a different VM running elsewhere, I didn't get any traces and tcpdump kept showing UDP error, it could have been because of the our corp network, will debug it more to see if I can consistently reproduce the issue in a different network setup

**Comment by yurishkuro** [comment]
@bharat-p fyi, the main UDP sender was really not meant to be used over the network, the main assumption was that the agent would run on the same host and the UDP connection will be to 127.0.0.1

If you cannot make such deployment work, I think a better option would be to implement an HTTP sender. In fact, in that case you won't even need to run the agent, because we're adding HTTP endpoints to the collectors directly.

The Java and Go clients already have HTTP-based reporters.

**Comment by bendemaree** [comment]
@yurishkuro I'm happy to add a test, yes. Should I hold off? Like @bharat-p I had difficulties getting requests to actually hit the agent, even after the updated host. The localhost-only strategy is an impediment for me locally and in a potential deployment; I'd hope to have the Jaeger stack pulled in for local development with docker-compose and in a potential deployment, as a sidecar to a Kubernetes deployment (with N homogenous pods on a node talking to a Jaeger agent on that node).

How much effort do you think adding an HTTP sender is? I can attempt adding that but I could use some high-level implementation guidance.

**Comment by yurishkuro** [comment]
@bendemaree  Given that using another host doesn't work too well, I think it makes sense not to merge this at all. Could you explain though why you cannot run the agent as a side car on the same bare metal host?  E.g. NewRelic is using the same mechanism as Jaeger: https://github.com/kubernetes/kubernetes/tree/master/examples/newrelic

**Comment by bendemaree** [comment]
@yurishkuro Whoops, I messed up there; I see now that `localhost` should work fine under Kube. Thanks. 😁 

I agree; if this enables broken configuration it should just be closed. ISTM the issue for folks here (myself included) is running the agent as part of a local Docker stack in which `localhost` isn't available for the agent. I just want to clarify that implementing the HTTP sender is the path forward here; is there some other option that should be considered?

**Comment by yurishkuro** [comment]
Technically there are many options of getting spans out of process, e.g. gRPC or Kafka, but we want to balance it against adding more dependencies to the library. An HTTP sender can be implemented with the dependencies we already have, and it works better than UDP when the agent on the same host is not available (e.g. we have a similar use case when running some services in the cloud).

**Comment by bharat-p** [comment]
@bendemaree / @yurishkuro  Would you mind explaining how it works in K8S world  ( I am not too familiar with it). How does a service running in K8S as container can reach agent ( which probably is running in another container) via `localhost`?

**Comment by yurishkuro** [comment]
@bharat-p you may want to take a look at https://github.com/jaegertracing/jaeger-kubernetes, and also open a ticket there if you have questions like ^^ (I'm not sure I know the correct answer as we're not running Jaeger on K8S internally).

**Comment by pavolloffay** [comment]
I'm syncing on this, k8s templates require you to configure the address to point to the agent/(or collector) as the agent/collector does not run on localhost. 

In production k8s/openshift templates we decided to run agent as https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/ so all pods on the same node will send spans to the same agent. The agent address is not a `localhost` but something like this `jaeger-agent.${NAMESPACE}.svc.cluster.local`. It means that data will go through some virtual interfaces to reach the right pod, I'm not sure if this can mean that some data can be lost compared to running it to `localhost`

cc @jpkrohling.

**Comment by bharat-p** [comment]
Thanks @pavolloffay , so I guess this PR is still relevant as without it we won't be able to configure client to send trace info to agent address like `jaeger-agent.${NAMESPACE}.svc.cluster.local`

**Comment by yurishkuro** [comment]
@bharat-p +1. Can you add a unit test for this property? Then we can merge.

**Comment by bharat-p** [comment]
Original PR was opened by @bendemaree , he will have to add UT for new config. If he's ok, I can open a new PR with his change + UT.

**Comment by yurishkuro** [comment]
oh, sorry - yeah, either way.

**Comment by bendemaree** [comment]
I'll get a test up today!

**Comment by 23doors** [comment]
Any progress on that?

**Comment by bharat-p** [comment]
@bendemaree if you are tied up with other things, let me know and I will open a new PR with UT to get this merged in. Thanks.

**Comment by bharat-p** [comment]
Opened a new PR https://github.com/uber/jaeger-client-python/pull/51 with @bendemaree 's changes alsong with UT to test new config.

**Comment by yurishkuro** [comment]
Closing, done in #51

**Pull request closed without merging**
