### PR TITLE
Fixing typo in README, missing (')

### PR DESCRIPTION
**Pull request by guillermo-sentinella**
Trying to use the examples I realized a missing character (') on:

service_name='your-app-name

if you copy/paste the code, did not work.

### CODE REVIEW

**Comment by black-adder** [comment]
Thanks, can you sign the CLA and we can land this

**Comment by guillermo-sentinella** [comment]
Hi @black-adder  I need to commit the change  again because I didnt configured my email so Iḿ not able to sign the CLA, another question, how ca I my emial/user to the LICENSE file? Regarding to this: If you contribute to a file in this project and are not an Uber employee, then you should add your name to the copyright section of the licence file.

Thanks

**Comment by guillermo-sentinella** [comment]
Hello again @black-adder I Already signed the CLA, can you land this?

**Comment by guillermo-sentinella** [comment]
I am not able to change the author of first commit, please close this pull request. I will send a new pull request with author and CLA signed correctly. Thanks for your patience

**Pull request closed without merging**
